// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoyBVBCn4Dm5I_HWXSWh8XkAuLLWLXbFg',
    appId: '1:1047189506627:android:0120ee11aadc22d85762f6',
    messagingSenderId: '1047189506627',
    projectId: 'chatup-4ff27',
    storageBucket: 'chatup-4ff27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfuoNB9wssAz5-56rn6X4O1NI8BQ_EMQ',
    appId: '1:1047189506627:ios:4ea5fef89dc86aaa5762f6',
    messagingSenderId: '1047189506627',
    projectId: 'chatup-4ff27',
    storageBucket: 'chatup-4ff27.appspot.com',
    androidClientId: '1047189506627-jumv961ne8c0vfui2qhtdr91fhkd2qst.apps.googleusercontent.com',
    iosClientId: '1047189506627-se3lvq4oajppg511qrhhtekthtuc4fhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.minorproject',
  );
}
